AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
